Resources:
   Bucket:
     Type: 'AWS::S3::Bucket'
     Properties:
	     BucketName: 'catpicsfeb162022'
   Instance:
     Type: 'AWS::EC2::Instance'
     Properties:
       KeyName: 'A4L'
       InstanceType: 't2.micro'
       ImageId:  'ami-033b95fb8079dc481'